# -*- coding: utf-8 -*-
"""식물진단_고정.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JzaQ2MNQQAjAlhOecdY78a_CGHXa0Tvm
"""

from fastai.vision.all import *
from fastai.vision import *
import numpy as np
from pathlib import Path
from fastai.vision.utils import verify_images
from fastai.vision.data import ImageDataLoaders
from fastai.vision.augment import aug_transforms
from fastai.vision.data import imagenet_stats
from torchvision.transforms import Normalize











