# -*- coding: utf-8 -*-
"""식물진단_실행.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z8D5RvI3TiIXIyWxTF7Xoq9ZzsF38J7M
"""

import cv2
from lib import *
import pickle
import pathlib

# 이미지 파일 불러오기
img_path = 'C:\\Users\\smhrd\\Desktop\\HGY\\Flask\\Plant\\data\\Mosaic.jpg'
img = cv2.imread(img_path)

# 모델 불러오기 (모델 파일의 경로를 입력해야 합니다)
posix_backup = pathlib.PosixPath
try:
  pathlib.PosixPath = pathlib.WindowsPath
  model_path = 'C:\\Users\\smhrd\\Desktop\\HGY\\Flask\\Plant\\export.pkl'
  learn = load_learner(model_path)
finally:
  pathlib.PosixPath = posix_backup

# 예측 수행
p = learn.predict(img)
category=str(p[0]).replace("Category ","")
if category=="export.pkl":
  illname="healthy"
else:
  illname=category
imageinfo = "Condition : "+illname
print(imageinfo)